/**
 * Plain-text export for sharing or saving outside the app.
 */
export function buildItineraryExportText({ destination, days, people, budget, itinerary, hotels, tips }) {
  const lines = [];
  lines.push('TripAddicts — Trip plan');
  lines.push('═'.repeat(36));
  lines.push(`Destination: ${destination || '—'}`);
  if (days) lines.push(`Duration: ${days} days`);
  if (people && Number(people) > 1) lines.push(`Travelers: ${people}`);
  if (budget) lines.push(`Budget (approx.): ₹${Number(budget).toLocaleString('en-IN')}`);
  lines.push('');

  if (itinerary?.length) {
    lines.push('ITINERARY');
    lines.push('-'.repeat(36));
    itinerary.forEach((day) => {
      lines.push(`Day ${day.day}${day.theme ? ` — ${day.theme}` : ''}`);
      (day.activities || []).forEach((a) => lines.push(`  • ${a}`));
      lines.push('');
    });
  }

  if (hotels?.length) {
    lines.push('STAYS');
    lines.push('-'.repeat(36));
    hotels.forEach((h) => {
      lines.push(`  • ${h.name} — ${h.type || 'Stay'} — ₹${h.price?.toLocaleString?.('en-IN') ?? h.price}/night`);
    });
    lines.push('');
  }

  if (tips?.length) {
    lines.push('TIPS');
    lines.push('-'.repeat(36));
    tips.forEach((t, i) => lines.push(`  ${i + 1}. ${t}`));
  }

  lines.push('');
  lines.push('Generated by TripAddicts');
  return lines.join('\n');
}
